plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
name: Monite task solution
title: null
include:
  - solution.md
github:
  is_project_page: false